server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_portal
    username: portal_user
    password: portal_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect